AllCops:
  TargetRubyVersion: 2.7
  Exclude:
    - 'node_modules/**/*'
    - '.next/**/*'
    - 'var/**/*'
    - 'build/**/*'

AsciiComments:
  Enabled: false

Style/StderrPuts:
  Enabled: false

Metrics/MethodLength:
  Max: 60
  Exclude:
    - 'launcher/launcher.rb'
    - 'spec/large/**/*.rb'

Metrics/BlockLength:
  Exclude:
    - 'launcher/launcher.rb'
    - 'spec/**/*.rb'

Naming/FileName:
  Enabled: false

Style/Documentation:
  Enabled: false

# https://docs.rubocop.org/rubocop/cops_metrics.html
Metrics/AbcSize:
  Max: 32  # 36
  Exclude:
    - 'launcher/launcher.rb'
    - 'launcher/AppLauncher/ALTaskExec.rb'  # TODO

Metrics/CyclomaticComplexity:
  Exclude:
    - 'launcher/launcher.rb'
    - 'launcher/lib/Executor.rb'  # TODO

Metrics/PerceivedComplexity:
  Exclude:
    - 'launcher/launcher.rb'
    - 'launcher/lib/Executor.rb'  # TODO

Style/ClassVars:
  Enabled: false

Lint/EmptyWhen:
  Enabled: false
