services:
  web:
    image: maisandbox3-web
    container_name: maisandbox3-web
    build:
      context: ../
      dockerfile: docker/web/Dockerfile
    restart: always
    user: 1100:1100
    ports:
      - 11460:11460
    volumes:
      - var:/var/opt/msb:rw
    environment:
      - LAUNCHER_PROCESS=SOCKET 
      - LAUNCHER_SOCKET_PATH=/var/opt/msb/launcher.sock
      - NODE_ENV=production
      - FRONTEND=static
    working_dir: /opt/msb
    command: node build/app/MainServer.js
  runner:
    image: maisandbox3-runner
    container_name: maisandbox3-runner
    build:
      context: ../
      dockerfile: docker/base/Dockerfile
    restart: always
    user: 1000:1000
    volumes:
      - var:/var/opt/msb:rw
    working_dir: /opt/msb
    command: ruby /opt/msb/deps/applauncher/index.rb --workdir /tmp/msb --unixsocket /var/opt/msb/launcher.sock

volumes:
  var: