name: lint

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-20.04
    
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.7'
    - uses: actions/setup-node@v1
      with:
        node-version: '12'
    - name: Please tell me who you are.
      run: |
        git config --global user.email "mai@ukibune.net"
        git config --global user.name "mai bot-worker"
    - name: install tools
      run: |
        sudo apt update
        sudo apt install g++
        sudo npm i -g yarn
        gem install bundler
    - name: install packages
      run: |
        yarn
        bundle install
    - name: lint javascript
      run: |
        yarn lint-fix
    - name: lint ruby
      run: |
        bundle exec rubocop --auto-correct
    - name: commit phase
      run: |
        if [ `git diff | wc -l` -ne 0 ] ; then
        git add .
        git commit -m 'lint-fix by Github Actions'
        fi
    - name: Push
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
