name: test-run

on: [push]

jobs:
  build:
    strategy:
      matrix:
        node: [12, 14]

    runs-on: ubuntu-20.04
    
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.7'
    - name: get git submodules
      run: |
        git submodule init
        git submodule update
    - name: install tools
      run: |
        sudo apt update
        sudo apt install g++
        sudo npm i -g yarn
    - name: install packages
      run: |
        yarn
    - name: test launch develop
      run: |
        PORT=3030 timeout 20 yarn dev || [[ $? -eq 124 ]]
    - name: test launch production
      run: |
        yarn build
        yarn --production
        ruby deps/applauncher/index.rb --verbose &
        LAUNCHER_PROCESS=SOCKET timeout 20 yarn prod || [[ $? -eq 124 ]]
