name: test-run

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        node: [18, 20]

    runs-on: ubuntu-20.04
    
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.7'
    - name: get git submodules
      run: |
        git submodule init
        git submodule update
    - name: install packages
      run: |
        yarn
    - name: test launch develop
      run: |
        PORT=3030 timeout 10 yarn dev || [[ $? -eq 124 ]]
    - name: test launch production
      run: |
        yarn build
        yarn --production
        ruby deps/applauncher/index.rb --verbose &
        LAUNCHER_PROCESS=SOCKET timeout 20 yarn prod || [[ $? -eq 124 ]]
