name: upgrade-dependency-packages-minor

# yarn upgrade
# Upgrade yarn.lock
# cf. yarn upgrade --latest
# 
# bundle update
# Upgrade Gemfile.lock

on:
  schedule:
    - cron: 0 12 * * 5  # At 12:00 on Friday.

jobs:
  build:
    strategy:
      matrix:
        node: [14, 16]

    runs-on: ubuntu-20.04
    
    steps:
    - uses: actions/checkout@v2
      with:
        ref: develop
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}
    - name: Please tell me who you are.
      run: |
        git config --global user.email "mai@ukibune.net"
        git config --global user.name "mai bot-worker"
    - name: get git submodules
      run: |
        git submodule init
        git submodule update
    - name: upgrade packages (light)
      run: |
        npm i -g npm-check-updates
        npx npm-check-updates -u -t patch
        yarn upgrade
    - name: presubmit
      id: presubmit
      run: |
        ./presubmit.sh
        ./presubmit.sh
        # test launch develop
        PORT=3030 timeout 20 yarn dev || [[ $? -eq 124 ]]
    - name: commit phase
      if: "${{ steps.presubmit.conclusion != 'skip' }}"
      run: |
        if [ `git diff | wc -l` -ne 0 ] ; then
        git add package.json yarn.lock
        git commit -m 'upgrade by Github Actions'
        fi
    - name: push
      if: "${{ steps.presubmit.conclusion == 'success' }}"
      run: |
        git push origin || :
    - name: Create Pull Request
      if: "${{ steps.presubmit.conclusion == 'failure' }}"
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        author: mai bot-worker <mai@ukibune.net>
