name: upgrade-dependency-packages-minor

# yarn upgrade
# Upgrade yarn.lock
# cf. yarn upgrade --latest
# 
# bundle update
# Upgrade Gemfile.lock

on:
  schedule:
    - cron: 0 12 * * 5  # At 12:00 on Friday.

jobs:
  build:

    runs-on: ubuntu-20.04
    
    steps:
    - uses: actions/checkout@v2
      with:
        ref: develop
    - uses: actions/setup-node@v1
      with:
        node-version: '12'
    - name: Please tell me who you are.
      run: |
        git config --global user.email "mai@ukibune.net"
        git config --global user.name "mai bot-worker"
    - name: get git submodules
      run: |
        git submodule init
        git submodule update
    - name: install tools
      run: |
        sudo apt update
        sudo npm i -g yarn
    - name: upgrade packages (light)
      run: |
        yarn upgrade
    - name: presubmit
      run: |
        ./presubmit.sh
    - name: commit phase
      run: |
        if [ `git diff | wc -l` -ne 0 ] ; then
        git add package.json yarn.lock
        git commit -m 'upgrade by Github Actions'
        fi
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
